### ISSUE TITLE
What is conv_embed doing in ConvSeqEncoder class?

### ISSUE THREAD

**Issue by gitlabspy** [visinf/mar-scf#1]
I noticed `conv_embed` kinda mix all elements of a batch along the channels before they are passed through `conv_lstm`. I wonder why your doing this 😃 
BTW, I love your work!

**Comment by gitlabspy** [comment]
I thought it might be for fixing the problem that the total channels of the input might be an odd number, right?

**Comment by apratimbhattacharyya18** [comment]
Hi, the ```conv_embed``` layer is applied for all channels and for all samples within the batch. This operation effectively captures spatial interactions within the channel (l_i^j) by increasing the spatial receptive field for each cell in the ConvLSTM. 
Hope this helps.
Thanks!
